=== ipdjac1/gh-pages/0 XMLDTD/contact3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generated by XMLSpy v2017 (x64) (http://www.altova.com) -->
<!-- In the XML document, <contacts> is the root element. you can see that the <contacts> element contains a
<contact> element. There is only one child element, so this content model should be easy to
define. -->
<!ELEMENT contacts (contact+)>
<!ELEMENT contact (name, location, phone, knows, description)>

<!--Declare the <phone> element in your DTD-->
<!ELEMENT phone (#PCDATA)>
<!--Declare the
<name> element and each of its children. The <first>, <middle>, and <last> elements represent
each part of the contact’s name. They are all text-only elements-->
<!ELEMENT name (first+, middle*, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!--The location declaration allows each location to include either an address or the latitude and
longitude coordinates.-->

<!ELEMENT location (address, (latitude, longitude)?)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT em (#PCDATA)>
<!--You must include declarations for the <em>, <strong>, and <br> elements-->
<!ELEMENT description (#PCDATA | em | br | strong)*>
<!--There is a <knows> element in the contacts.xml document-->
<!ELEMENT knows (#PCDATA)>
<!-- .#PCDATA is for "Joseph is an" and "XML!" can be added in several pieces -->
<!ELEMENT strong (#PCDATA)>
<!-- HTML element which is empty-->
<!ELEMENT br EMPTY>

<!-- . This time you’ll add
attributes to some of the elements to provide more information in the document. there are no constrains on the attibutes-->

<!ATTLIST knows
	contacts CDATA #IMPLIED
>
<!ATTLIST phone
	kind CDATA #IMPLIED
>
<!ATTLIST contact
	person CDATA #IMPLIED
	tags CDATA #IMPLIED
>
<!ATTLIST contacts
	source CDATA #IMPLIED
	version CDATA #IMPLIED
>

=== ipdjac1/gh-pages/0 XMLDTD/contacts3.xml
<?xml version="1.0"?>
<!DOCTYPE contacts SYSTEM "contact3.dtd">
<!-- Add a link to contacts3.dtd -->
<contacts source="XML Test 1" version="1.0 Fall 2016">
	<contact person="Joe_Fawcett" tags="XML developer">
		<name>
			<first>Joseph</first>
			<first>John</first>
			<last>Fawcett</last>
		</name>
		<location>
			<address>Exeter, UK</address>
			<latitude>50.7218</latitude>
			<longitude>-3.533617</longitude>
		</location>
		<phone kind="Home">001-234-567-8910</phone>
		<knows contacts="John_Doe Danny_Ayers"/>
		<description>Joseph is an <em>XML developer</em>.<br/>Joseph <strong>loves</strong> XML!</description>
	</contact>
	<contact person="John Doe" tags="XML consultant">
		<name>
			<first>John</first>
			<last>Doe</last>
		</name>
		<location>
			<address>Address is not known</address>
		</location>
		<phone>321 321 3213</phone>
		<knows contacts="Joseph Fawcett Danny_Ayers"/>
		<description>Senior Technical Consultant for LMX.</description>
	</contact>
</contacts>
